apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sca.secret_name }}
  labels:
    {{- include "swc-k8s.labels" . | nindent 4 }}
data:
  service_key: {{ .Values.sca.service_key | b64enc }}
type: Opaque
